export const DELETE_USER = 'USERS:DELETE_USER';
export const DELETE_USER_FROM_REDUX = 'USERS:DELETE_USER_FROM_REDUX';
export const GET_USER_LIST = 'USERS:GET_USER_LIST';
export const SET_USER_LIST = 'USERS:SET_USER_LIST';
export const SET_USER = 'USERS:SET_USER';
export const UPDATE_USER = 'USERS:UPDATE_USER';
